name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          check-latest: true

      - name: Compile Java Code
        run: javac HelloWorldApp.java

      - name: Run Java Application
        run: java HelloWorldApp
        
      - name: Success Notify
        run: echo "This job's status is ${{ job.status }}."
