name: Deploy Python Website
on: [push]
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.16'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python tests.py

      - name: Deploy (Run Flask App)
        run: |
          nohup python app.py &
          sleep 5
          curl -I http://127.0.0.1:5000 | grep "200 OK"
